name: spreadinterp
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - cuda-version
  - cuda-libraries-dev
  - cuda-nvcc
  - cuda-cudart
  - blas-devel
  - libblas
  - liblapacke
  - cmake
  - make
  - gxx
  - pytest
  - cupy
  - numpy
  - pip:
    - sphinx==8.2.3
    - sphinx-rtd-theme==3.0.2
    - sphinxcontrib-autoprogram==0.1.9
    - sphinxcontrib-napoleon==0.7
    - gitpython

